package roketto.oracle.apps.fusion.cf.model.adfbc.services;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 02 22:21:00 AST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LookupsAMImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LookupsAMImpl() {
    }

    /**
     * Container's getter for Lookups1.
     * @return Lookups1
     */
    public ViewObjectImpl getLookupsVO1() {
        return (ViewObjectImpl) findViewObject("LookupsVO1");
    }

    /**
     * Container's getter for LookupTypes1.
     * @return LookupTypes1
     */
    public ViewObjectImpl getLookupTypesVO1() {
        return (ViewObjectImpl) findViewObject("LookupTypesVO1");
    }

    /**
     * Container's getter for LookupValues1.
     * @return LookupValues1
     */
    public ViewObjectImpl getLookupValuesVO1() {
        return (ViewObjectImpl) findViewObject("LookupValuesVO1");
    }
}

