package com.oracle.xmlns.oxp.service.v2;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class ReportServiceClient {
    public static void main(String[] args) {
        ReportService_Service reportService_Service = new ReportService_Service();
        ReportService reportService = reportService_Service.getReportService();
        // Add your code to call the desired methods.


    }
}
